status = [
    "build (ubuntu-latest, stable)",
    "build (ubuntu-latest, nightly)",
    "build (windows-latest, stable)",
    "build (windows-latest, nightly)",
    "build (macOS-latest, stable)",
    "build (macOS-latest, nightly)",
]
delete-merged-branches = true
